### ISSUE TITLE
errors running `cargo run --release`

### ISSUE THREAD

**Issue by acheronfail** [aochagavia/rocket#69]
Hi there, I'm attempting to run `cargo run --release` and I'm running into 19 errors which are all similar to:

```
error: type `private::ffi::CGSRegionObject` is private
  --> /Users/<user>/.cargo/registry/src/github.com-1ecc6299db9ec823/core-graphics-0.3.2/src/private.rs:81:21
   |
81 |             assert!(ffi::CGSSetSurfaceShape(self.context_id,
   |
```

I'm running `rustc 1.22.1` and I'm on `macOS 10.12.6`. Any idea what could be causing this issue?

**Comment by aochagavia** [comment]
There is something weird going on here... This is a compilation error, so there must be something wrong with the dependencies. I cannot reproduce it on Windows, though.

I am getting tired of Piston, to be honest. It has a huge dependency tree, takes ages to compile and results in this kind of stuff. I think this will provide the motivation I need to switch to something else, like ggez.

By the way, would you be interested in helping port the game to ggez?

**Comment by acheronfail** [comment]
Well, I came across this repo because I wanted to experiment with Rust by making a game, I suppose helping port it over would be just as good! 

So yes, I'd definitely be interested in helping out 👍

**Comment by aochagavia** [comment]
Great! Right now, the following files depend on Piston:

* `input.rs`: we use Piston to know which keys are pressed and the movements of a controller, should there be one.
* `main.rs`: we use Piston to create the window and process events (`while let Some(e) = window.next()`)
* `view.rs`: we use Piston to draw to the screen

The goal is to remove all usages of Piston in those files and replace that by stuff from the ggez crate. I have never worked with ggez before, but I have looked at a bunch of [examples](https://github.com/ggez/ggez/tree/master/examples) and it seems doable.

Feel free to ask any questions you have, also about Rust itself!

**Comment by acheronfail** [comment]
@aochagavia I've started to port it over [here](https://github.com/acheronfail/rocket/commit/783351eaed8b17d1a7e77b063bae4579910f6f02) and it's working alright, though I have some problems I'm not sure how to solve:

1. I haven't figured out a way to make the `PLAYER_POLYGON` a constant as a slice of `ggez::graphics::Point2` points, so [unfortunately it's re-computed every time](https://github.com/acheronfail/rocket/blob/783351eaed8b17d1a7e77b063bae4579910f6f02/src/view.rs#L87-L91).
2. Not sure how I can use the `Color` mod from `src/drawing.rs`, it would be better than [hardcoding](https://github.com/acheronfail/rocket/blob/1bcbb8928c147a8084543bfc94872252576fff51/src/view.rs#L31) it like I do now. I'm not sure how to combat this since `ggez` wants the `Color` struct initialised...
3. When there are explosions there's considerable lag. I haven't played the original game using Piston so I'm not sure if that's normal or not.
4. I also couldn't get it working if I added `ggez` into the `Cargo.toml` file as a dependency? So I added it as a git dependency instead (which is what [this ggez showcase did](https://github.com/dpogretskiy/specs-ggez-showcase))

These errors might just be since I don't have a tonne of experience with Rust yet! 😅

**Comment by aochagavia** [comment]
Good to see you are making progress!

Regarding your issues:

1. I don't think this is a problem. Re-computing the polygon every time is very cheap and likely to be optimized away.
2. It is possible to inintialize the colors in a const by using the struct syntax. For instance `const RED: Color = Color { r: 1.0, g: 0.0, b: 0.0, a: 1.0 }` (if the [documentation](https://docs.rs/ggez/0.3.4/ggez/graphics/struct.Color.html) of color is up to date)
3. The explosion thing is a common problem when you are drawing lots of stuff. Basically, you are sending each ellipse separately to the graphics card, which is very inefficient. The best solution for this is to group all particles together in a single batch and send that to the graphics card. There is a new feature in ggez that does exactly this. It is called [SpriteBatch](https://github.com/ggez/ggez/blob/76ebe43ab153fa8bb48cb5dd6ed42df8028806a4/src/graphics/spritebatch.rs#L29). I would suggest you try it out. Feel free to ask questions about it, though, since it might get a bit complex.
4. The problem with adding `ggez` to `Cargo.toml` is probably related to the fact that the master branch has new features that haven't yet been released to crates.io. It is ok to use the git branch for now, but I think we should switch to crates.io when a new version is released.

Some additional comments:

1. I would suggest we remove controller support. I don't have controllers either so am also unable to test the feature.
1. I left some comments on the code, but they are mostly about style, so you can ignore them if you want

Keep up the good work! And again, feel free to ask any questions you have.

**Comment by acheronfail** [comment]
I've been looking at `SpriteBatch` but I'm not sure I'm entirely getting it. It seems to require an image to be used? When we just want to render circles...

Should we be creating an image of a circle and using that with `SpriteBatch`, or is there a way to draw a circle into an image at runtime?

Otherwise I'm a little stumped as to how this can solve our particle drawing problem. 😅

**Comment by aochagavia** [comment]
I would expect there to be a way of drawing images at runtime. It looks like [this function](https://docs.rs/ggez/0.3.4/ggez/graphics/type.Image.html#method.from_rgba8) allows that. However, it expects a bitmap as a parameter, which is kind of annoying because it means you first need to generate a bitmap of the circle. As far as I know, there are no functions available to generate the bitmap of a circle.

I suggest you use `Image::solid` for debugging (see [the docs](https://docs.rs/ggez/0.3.4/ggez/graphics/type.Image.html#method.solid) for details). This way we can test whether `SpriteBatch` solves the slowdown. After that, the next step would be to open an issue on ggez's repository to request the feature of drawing to an image or asking for advice on how to approach the problem.

**Comment by acheronfail** [comment]
Awesome, thanks 😄 

I got it working with SpriteBatch, I'll show you the difference:

Normally:
https://www.dropbox.com/s/soo51i4pgi1fq6d/normal.mov?dl=0

Using SpriteBatch:
https://www.dropbox.com/s/prkcvcrc7mf6cbd/spritebatch.mov?dl=0

So I think it improves performance a little, but there is still some lag.
I'm running this on a decent machine: `3.3 GHz Intel Core i7`

**Comment by acheronfail** [comment]
Turns out building with the `--release` flag improves performance by a considerable margin! I get no jankiness or lag if I build with `cargo run --release`. 👍 

Edit: In fact, it even works smoothly without using `SpriteBatch` at all, all we needed to do was use `opt-level=1` or build for release!

**Comment by aochagavia** [comment]
Nice to see you found the root of the problem! Forgetting to turn on optimizations is kind of a rite of passage in Rust. I suggest we discuss further in the PR thread.
