### ISSUE TITLE
Investigate possibility of adding sound

### ISSUE THREAD

**Issue by aochagavia** [aochagavia/rocket#72]
I tried to add sound effects when we were using Piston, but didn't manage to get it working. It seems that ggez supports this out of the box, so it would be interesting to give this another go.

cc @acheronfail

**Comment by acheronfail** [comment]
I was thinking about this too - I'm keen to give it a go. Unless you have some sound effects I suppose we'll have to find some. 

Some suggestions after a quick web search:

- Game start/restart
    - https://freesound.org/people/GameAudio/sounds/220173/
    - https://freesound.org/people/LittleRobotSoundFactory/sounds/274184/
- Enemy spawn
    - https://freesound.org/people/Kastenfrosch/sounds/162478/
    - https://freesound.org/people/GameAudio/sounds/220202/
    - https://freesound.org/people/GameAudio/sounds/220191/
    - https://freesound.org/people/GameAudio/sounds/220165/
    - https://freesound.org/people/LittleRobotSoundFactory/sounds/288965/
    - https://freesound.org/people/LittleRobotSoundFactory/sounds/274211/
- Enemy killed
    - https://freesound.org/people/LittleRobotSoundFactory/sounds/290380/
    - https://freesound.org/people/LittleRobotSoundFactory/sounds/270332/
- Shot fired
    - https://freesound.org/people/LittleRobotSoundFactory/sounds/270536/
    - https://freesound.org/people/LittleRobotSoundFactory/sounds/270344/
    - https://freesound.org/people/LittleRobotSoundFactory/sounds/270343/
    - https://freesound.org/people/GameAudio/sounds/220206/
- Player killed
    - https://freesound.org/people/LittleRobotSoundFactory/sounds/270328/
    - https://freesound.org/people/LittleRobotSoundFactory/sounds/270334/
    - https://freesound.org/people/LittleRobotSoundFactory/sounds/270553/
- For every 1,000 points?
    - https://freesound.org/people/GameAudio/sounds/220184/
- Boost
    - couldn't find anything
- We could also have a track looping in the background?
    - could have a "booster" loop which is the player's engine
    - increase the intensity of this sound while the player boosts

Some of these are pretty lame - I would like some better/more appropriate sounds...

If this is implemented, I would suggest having some delays in the app: maybe a 3 sec countdown each time it starts/restarts. Otherwise I can see the sound effects getting annoying and/or overlapping in not nice ways.

**Comment by aochagavia** [comment]
Wow, that is a nice collection of sounds! I would rather use an explosion sound when the player is killed, though, something like:

* https://freesound.org/people/ryansnook/sounds/110111/
* https://freesound.org/people/dogfishkid/sounds/399303/
* https://freesound.org/people/tommccann/sounds/235968/

Regarding the delays, I completely agree. We could even show a game over screen after the player is killed, along the following lines: *Game Over \n Press any key to restart*.

**Comment by johnthagen** [comment]
If you are interested in [`piston-music`](https://crates.io/crates/piston-music) you can see `rust-belt` for our [sound/music implementation](https://github.com/johnthagen/rust-belt/blob/master/src/menu.rs#L60).
